import {test} from 'node:test';
import assert from 'node:assert/strict';
const origin='http://localhost:3000';
let cookie='';
async function request(path,{data,auth=true,originHeader=origin}={}){const r=await fetch(origin+'/api/store/'+path,{method:data===undefined?'GET':'POST',headers:{...(auth?{Cookie:cookie}:{}),...(data===undefined?{}:{'Content-Type':'application/json',Origin:originHeader})},body:data===undefined?undefined:JSON.stringify(data)});const text=await r.text();let parsed=null;try{parsed=JSON.parse(text)}catch{}return {status:r.status,data:parsed,raw:text};}
test('storefront routes, accounts, owner permissions, catalog, carts, favorites and events',async(t)=>{
 const login=await fetch(origin+'/signin-with-chatgpt?return_to=/account',{redirect:'manual'});assert.equal(login.status,302);cookie=login.headers.get('set-cookie').split(';')[0];
 await t.test('all pages respond successfully and unknown page returns 404',async()=>{for(const p of ['/','/software','/software/signova-connect','/software/signova-play-starter','/software/event-access-kit','/shop','/game','/events','/news','/login','/account','/admin','/cart','/policies','/shop/sample-vase']){const r=await fetch(origin+p);assert.equal(r.status,200,p);}for(const file of ['signova-connect.zip','signova-play-starter.zip','event-access-kit.zip']){const r=await fetch(origin+'/downloads/'+file);assert.equal(r.status,200,file);const bytes=new Uint8Array(await r.arrayBuffer());assert.equal(String.fromCharCode(bytes[0],bytes[1]),'PK',file);}assert.equal((await fetch(origin+'/does-not-exist')).status,404);});
 await t.test('anonymous access and forged-origin writes are rejected',async()=>{assert.equal((await request('me',{auth:false})).data.user,null);assert.equal((await request('admin',{auth:false})).status,401);assert.equal((await request('cart',{auth:false})).status,401);assert.equal((await request('profile',{data:{name:'Wrong'},originHeader:'https://attacker.invalid'})).status,403);});
 await t.test('existing identity has a persistent profile and owner role',async()=>{assert.equal((await request('me')).data.user.admin,true);assert.equal((await request('profile',{data:{name:'Integration Check'}})).status,200);assert.equal((await request('me')).data.user.name,'Integration Check');await request('profile',{data:{name:'Seedy'}});});
 await t.test('sample products cannot be added to cart; checkout cannot fake a payment',async()=>{assert.equal((await request('cart',{data:{productId:'sample-vase',quantity:1}})).status,404);assert.equal((await request('checkout',{data:{}})).status,503);assert.equal((await request('verify',{data:{orderId:'invented'}})).status,404);});
 const product={title:'QA temporary item',description:'Only for automated local validation.',category:'Home & living',price:4500,stock:3,image:'/hero.png',status:'draft'};let id;
 await t.test('admin can save a draft; draft stays out of public catalog',async()=>{const r=await request('admin/product',{data:product});assert.equal(r.status,200);id=r.data.id;assert.ok(!(await request('catalog')).data.products.some(p=>p.id===id));});
 await t.test('publishing, inventory validation, and stale stock protection work',async()=>{assert.equal((await request('admin/product',{data:{...product,id,expectedStock:3,status:'published'}})).status,200);assert.ok((await request('catalog')).data.products.some(p=>p.id===id));assert.equal((await request('admin/product',{data:{...product,id,expectedStock:2,title:'Stale edit'}})).status,409);assert.equal((await request('cart',{data:{productId:id,quantity:4}})).status,409);assert.equal((await request('cart',{data:{productId:id,quantity:-1}})).status,400);});
 await t.test('cart changes persist and favorites can be saved and removed',async()=>{assert.equal((await request('cart',{data:{productId:id,quantity:2}})).status,200);assert.equal((await request('cart')).data.items.find(p=>p.id===id).quantity,2);await request('favorite',{data:{productId:id,saved:true}});assert.ok((await request('favorites')).data.includes(id));await request('favorite',{data:{productId:id,saved:false}});assert.ok(!(await request('favorites')).data.includes(id));await request('cart',{data:{productId:id,quantity:0}});assert.ok(!(await request('cart')).data.items.some(p=>p.id===id));});
 let postId;const post={kind:'event',title:'QA temporary event',summary:'Local test.',body:'Not a real event.',date:new Date(Date.now()+86400000*60).toISOString(),location:'Local test space',image:'/hero.png',published:true};
 await t.test('events publish and RSVPs persist and can be cancelled',async()=>{const r=await request('admin/post',{data:post});assert.equal(r.status,200);postId=r.data.id;assert.ok((await request('content')).data.posts.some(p=>p.id===postId));assert.equal((await request('rsvp',{data:{postId,attending:true}})).status,200);assert.ok((await request('account')).data.rsvps.some(p=>p.id===postId));await request('rsvp',{data:{postId,attending:false}});assert.ok(!(await request('account')).data.rsvps.some(p=>p.id===postId));});
 await t.test('owner newsroom saves video stories and can delete them',async()=>{const news={kind:'news',title:'QA video story',summary:'A video and text test.',body:'First paragraph.\n\nSecond paragraph.',date:new Date().toISOString(),author:'Signova Technology',published_at:Date.now(),image:'/hero.png',video:'https://www.youtube.com/watch?v=dQw4w9WgXcQ',published:true,featured:true};const created=await request('admin/post',{data:news});assert.equal(created.status,200);const detail=await request('content/'+created.data.id);assert.equal(detail.data.post.video,news.video);assert.equal((await fetch(origin+'/news/'+created.data.id)).status,200);assert.equal((await request('admin/post-delete',{data:{id:created.data.id}})).status,200);assert.equal((await request('content/'+created.data.id)).status,404);});
 await t.test('personal best stores only valid, improved game results',async()=>{assert.equal((await request('score',{data:{moves:7,seconds:20}})).status,400);await request('score',{data:{moves:12,seconds:30}});await request('score',{data:{moves:20,seconds:40}});assert.ok((await request('account')).data.score.moves<=12);});
 await t.test('payment setup cannot activate without a connected account',async()=>{assert.equal((await request('admin/settings',{data:{shop_name:'Noble & New',support:'shop@example.com',returns:'Test returns',shipping:500,selling:true}})).status,400);assert.equal((await request('admin/connect',{data:{key:'not-a-key'}})).status,400);const r=await fetch(origin+'/api/stripe/webhook',{method:'POST',body:JSON.stringify({livemode:false})});assert.equal(r.status,503);});
 await t.test('image and video uploads validate format and serve uploaded bytes',async()=>{const bad=new FormData();bad.set('file',new Blob(['not an image'],{type:'image/png'}),'bad.png');assert.equal((await fetch(origin+'/api/upload',{method:'POST',headers:{Cookie:cookie,Origin:origin},body:bad})).status,400);const image=new FormData();const png=Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jBZkAAAAASUVORK5CYII=','base64');image.set('file',new Blob([png],{type:'image/png'}),'pixel.png');const r=await fetch(origin+'/api/upload',{method:'POST',headers:{Cookie:cookie,Origin:origin},body:image});assert.equal(r.status,200);const d=await r.json();const asset=await fetch(origin+d.url);assert.equal(asset.status,200);assert.equal(asset.headers.get('content-type'),'image/png');assert.deepEqual(Buffer.from(await asset.arrayBuffer()),png);const video=new FormData();const mp4=Buffer.concat([Buffer.alloc(4),Buffer.from('ftyp'),Buffer.alloc(24)]);video.set('kind','video');video.set('file',new Blob([mp4],{type:'video/mp4'}),'clip.mp4');const vr=await fetch(origin+'/api/upload',{method:'POST',headers:{Cookie:cookie,Origin:origin},body:video});assert.equal(vr.status,200);const vd=await vr.json();const videoAsset=await fetch(origin+vd.url);assert.equal(videoAsset.headers.get('content-type'),'video/mp4');assert.deepEqual(Buffer.from(await videoAsset.arrayBuffer()),mp4);});
 await t.test('archiving products and unpublishing events removes them from public pages',async()=>{await request('admin/product',{data:{...product,id,expectedStock:3,status:'archived'}});await request('admin/post',{data:{...post,id:postId,published:false}});assert.ok(!(await request('catalog')).data.products.some(p=>p.id===id));assert.ok(!(await request('content')).data.posts.some(p=>p.id===postId));});
});
